/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.oasis.okt.mcs.app

import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test
    fun testGetMessage() {
        println("test")
    }
}
