/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("okt-mcs-fundamentals-conventions")
}

dependencies {
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.5.21")
}