/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    `java-library`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

group = projectGroup
version = projectVersion

publishing {
    publications {
        create<MavenPublication>("mcsLib") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            credentials {
                username = "6115da3efa25fa3e24ef4974"
                password = ")vf[Nze9PrU["
            }
            val releasesRepoUrl = uri("https://packages.aliyun.com/maven/repository/2128600-release-6m4wkH/")
            val snapshotsRepoUrl = uri("https://packages.aliyun.com/maven/repository/2128600-snapshot-vzRfBW/")
            url = if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl
        }
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
