/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("okt-mcs-common-conventions")
}
dependencies {
    api(platform("software.amazon.awssdk:bom:$awsSdkVersion"))
    api("software.amazon.awssdk:sqs:$awsSdkVersion")
    api("software.amazon.awssdk:s3:$awsSdkVersion")
}