/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.oasis.okt.mcs.list

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class LinkedListTest {
    @Test
    fun testConstructor() {
        val a = 1
        assertEquals(1,a)
    }
}
